### ISSUE TITLE
How To use

### ISSUE THREAD

**Issue by brennyB** [rine77/homeassistant-edupage#2]
Hi, 
i installed the integration and was able to configure and login.
but to be clear: i do not understand how to use. :-( 

is there a small tutorial somewhere to get an idea?

**Comment by brennyB** [comment]
i tried to get something done... but it seems that there is an issue with the integration...

i receive one entitie edupage_grades
  
as faar as i understood there should be more. 
So is there someone who was able to use this integration? 

thx for feedback

**Comment by rine77** [comment]
Hey brenny,
I appreciate your effort but I am out of time atm. Please give me some days to react properly to this issue.
THANKS!
best regards, RL

**Comment by brennyB** [comment]
Hi rine77 Thx for your message. I am trying hard :-)But it seems that I am doing something wrong.Only find one entity and this is empty 😭Looking forward to your reply.Best regards BrennyAm 11.09.2024 16:20 schrieb rine77 ***@***.***>:
Hey brenny,
I appreciate your effort but I am out of time atm. Please give me some days to react properly to this issue.
THANKS!
best regards, RL

**Comment by brennyB** [comment]
just checking.. 
anny news?

**Comment by rine77** [comment]
Yeah I was inspecting the whole thing and found a major change in the edupage-api-library since 0.11 release.
So I need to get further into this and I'm still trying to find time for it.
Since than:
The entity shouldnt be empty. The grades and some details are to be found as attributes in the entity.
best regards, RL

**Comment by mgrfilipmarek** [comment]
I can also help with testing. 
Currently I cannot even download it :( 
![image](https://github.com/user-attachments/assets/586b8b6b-401e-4378-bcb7-0de421841b30)

**Comment by rine77** [comment]
Hello @mgrfilipmarek ,

thanks for your feedback. ATM my project ist not available in HACS, you need to download and install it manually as describes in [README.md](https://github.com/rine77/homeassistant-edupage/blob/main/README.md)

best regards

PS: I'm still in time issues but raise priority for this project now because more people seem to use it. THANKS
